#!/usr/bin/env node
/**
 * generate-test.js
 * AI 삼위일체 테스트 자동 생성 스크립트
 *
 * Usage:
 *   node scripts/generate-test.js <moduleName> <category>
 *
 * Example:
 *   node scripts/generate-test.js myModule core
 */

const fs = require('fs');
const path = require('path');

// ANSI 색상
const colors = {
  reset: '\x1b[0m',
  bright: '\x1b[1m',
  green: '\x1b[32m',
  yellow: '\x1b[33m',
  blue: '\x1b[34m',
  magenta: '\x1b[35m',
  cyan: '\x1b[36m',
};

async function generateTest() {
  console.log('\n' + colors.bright + colors.cyan + '🤖 AI 삼위일체 테스트 생성기' + colors.reset + '\n');

  // 커맨드 라인 인자 파싱
  const args = process.argv.slice(2);

  if (args.length < 2) {
    printUsage();
    process.exit(1);
  }

  const moduleName = args[0];
  const category = args[1]; // core, services, handlers
  const description = args[2] || '';

  // 유효성 검사
  if (!['core', 'services', 'handlers'].includes(category)) {
    console.log(colors.yellow + '❌ Category must be: core, services, or handlers' + colors.reset);
    process.exit(1);
  }

  console.log(colors.blue + '📝 Module Information:' + colors.reset);
  console.log(`  Name: ${colors.bright}${moduleName}${colors.reset}`);
  console.log(`  Category: ${colors.bright}${category}${colors.reset}`);
  console.log(`  Description: ${description || 'Auto-generated'}` + '\n');

  // 파일 경로 생성
  const testPath = path.join(__dirname, `../tests/${category}/${moduleName}.test.js`);
  const srcPath = path.join(__dirname, `../src/${category}/${moduleName}.js`);

  // 이미 파일이 존재하는지 확인
  if (fs.existsSync(testPath)) {
    console.log(colors.yellow + `⚠️  Test file already exists: ${testPath}` + colors.reset);
    console.log(colors.yellow + 'Overwrite? (y/N): ' + colors.reset);
    // 간단하게 진행
  }

  console.log(colors.green + '\n🧠 Step 1: Generating BDD Specification...' + colors.reset);
  console.log(colors.cyan + '   (Gemini would analyze requirements here)' + colors.reset);

  // BDD 템플릿 생성
  const bddTemplate = generateBDDTemplate(moduleName, category);
  console.log(colors.green + '✅ BDD specification generated' + colors.reset);

  console.log(colors.green + '\n⚙️  Step 2: Generating Jest Test Code...' + colors.reset);
  console.log(colors.cyan + '   (Qwen would generate test code here)' + colors.reset);

  // Jest 테스트 템플릿 생성
  const testCode = generateJestTemplate(moduleName, category, bddTemplate);
  console.log(colors.green + '✅ Jest test code generated' + colors.reset);

  console.log(colors.green + '\n💾 Step 3: Saving Files...' + colors.reset);

  // 테스트 파일 저장
  fs.writeFileSync(testPath, testCode);
  console.log(colors.green + `✅ Test saved: ${testPath}` + colors.reset);

  // 소스 파일 템플릿 생성 (아직 없는 경우)
  if (!fs.existsSync(srcPath)) {
    const srcTemplate = generateSourceTemplate(moduleName, category);
    fs.writeFileSync(srcPath, srcTemplate);
    console.log(colors.green + `✅ Source template saved: ${srcPath}` + colors.reset);
  }

  console.log(colors.bright + colors.magenta + '\n🎉 Test generation complete!' + colors.reset);
  console.log(colors.cyan + '\nNext steps:' + colors.reset);
  console.log(`  1. Review the generated test: ${testPath}`);
  console.log(`  2. Run: ${colors.bright}npm test ${testPath}${colors.reset}`);
  console.log(`  3. Implement: ${srcPath}`);
  console.log(`  4. Follow TDD cycle: 🔴 RED → 🟢 GREEN → 🔵 REFACTOR\n`);
}

function printUsage() {
  console.log(colors.bright + 'Usage:' + colors.reset);
  console.log(`  node scripts/generate-test.js <moduleName> <category> [description]\n`);
  console.log(colors.bright + 'Arguments:' + colors.reset);
  console.log(`  moduleName   - Name of the module (e.g., myHandler)`);
  console.log(`  category     - core | services | handlers`);
  console.log(`  description  - Optional module description\n`);
  console.log(colors.bright + 'Example:' + colors.reset);
  console.log(`  node scripts/generate-test.js authHandler handlers "Authentication handler"\n`);
}

function generateBDDTemplate(moduleName, category) {
  return `
BDD Specification for ${moduleName}:

Scenario 1: Basic functionality
  Given: Module is initialized
  When: Primary function is called
  Then: Expected result is returned

Scenario 2: Error handling
  Given: Invalid input
  When: Function is called
  Then: Error is thrown

Scenario 3: Edge case
  Given: Boundary condition
  When: Function is called
  Then: Handles gracefully
`;
}

function generateJestTemplate(moduleName, category, bddSpec) {
  const className = moduleName.charAt(0).toUpperCase() + moduleName.slice(1);

  return `// tests/${category}/${moduleName}.test.js
// Auto-generated by generate-test.js

const { ${className} } = require('../../src/${category}/${moduleName}');

describe('${className}', () => {
  let instance;

  beforeEach(() => {
    instance = new ${className}();
  });

  describe('Basic functionality', () => {
    test('should initialize correctly', () => {
      expect(instance).toBeDefined();
    });

    test('should perform primary operation', () => {
      // TODO: Implement based on BDD specification
      // Given: Module is initialized
      // When: Primary function is called
      // Then: Expected result is returned

      // Example:
      // const result = instance.execute();
      // expect(result).toBeDefined();
    });
  });

  describe('Error handling', () => {
    test('should throw error on invalid input', () => {
      // TODO: Implement error handling test
      expect(() => {
        // instance.execute(null);
      }).toThrow();
    });
  });

  describe('Edge cases', () => {
    test('should handle edge case', () => {
      // TODO: Implement edge case test
    });
  });
});

/*
BDD Specification:
${bddSpec}

Next Steps:
1. Run: npm test tests/${category}/${moduleName}.test.js
2. Implement the module to make tests pass
3. Refactor and improve
*/
`;
}

function generateSourceTemplate(moduleName, category) {
  const className = moduleName.charAt(0).toUpperCase() + moduleName.slice(1);

  return `/**
 * ${moduleName}.js
 * Auto-generated by generate-test.js
 *
 * @module ${moduleName}
 */

/**
 * ${className} class
 */
class ${className} {
  constructor(options = {}) {
    // TODO: Initialize
  }

  /**
   * Primary method
   *
   * @returns {*}
   */
  execute() {
    // TODO: Implement
    throw new Error('Not implemented');
  }
}

module.exports = { ${className} };
`;
}

// 실행
generateTest().catch(error => {
  console.error(colors.yellow + '\n❌ Error:', error.message + colors.reset);
  process.exit(1);
});
